### PR TITLE
Refactor plugin to not rely on caching for writing anymore

### LINKED ISSUE #1: Password caching does not work when connecting to session
When connecting to a session from a different terminal it does not work, connecting to a session from the same terminal does work however.

### Steps to reproduce

```sh
sudo touch testfile
kak -s test -d
```
Close the terminal.
Then in a new terminal
```sh
kak -c test testfile
```
Then do `:sudo-write<ret>`

### Result

> Something went wrong

I retrieved some more debug info and `sudo -n` fails with: 
> a password is required

### Expected result

Writes to file

### PR DESCRIPTION
**Pull request by occivink**
Also test if the buffer is backed by a file, and fail if not

Fixes #1

### CODE REVIEW

**Comment by JJK96** [comment]
Looks okay to me, it asks for password every time when connected to another session, but it does cache the password if I don't connect to a session.
Which is probably the best we can achieve

**Comment by occivink** [comment]
Yeah, unfortunately this is outside of my hands as sudo doesn't really expose much to control the password caching.

**Comment by JJK96** [comment]
Not entirely related, but since this executes `dd` as root, maybe it is a good idea to guarantee that it can never accidentally write to something important like `/`

**Comment by occivink** [comment]
Can `dd of` even write to a directory? Another possibility would be to use
`sudo -- sh -c 'cat "$input" > "$output"'` I guess

**Comment by JJK96** [comment]
I just checked, it cannot write to a directory, so I think that should be safe

**Pull request merged**
